/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AbridgedFoodNutrient} from './AbridgedFoodNutrient';

/**
 * The AbridgedFoodItem model module.
 * @module model/AbridgedFoodItem
 * @version 1.0.1
 */
export class AbridgedFoodItem {
  /**
   * Constructs a new <code>AbridgedFoodItem</code>.
   * @alias module:model/AbridgedFoodItem
   * @class
   * @param dataType {String} 
   * @param description {String} 
   * @param fdcId {Number} 
   */
  constructor(dataType, description, fdcId) {
    this.dataType = dataType;
    this.description = description;
    this.fdcId = fdcId;
  }

  /**
   * Constructs a <code>AbridgedFoodItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AbridgedFoodItem} obj Optional instance to populate.
   * @return {module:model/AbridgedFoodItem} The populated <code>AbridgedFoodItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AbridgedFoodItem();
      if (data.hasOwnProperty('dataType'))
        obj.dataType = ApiClient.convertToType(data['dataType'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('fdcId'))
        obj.fdcId = ApiClient.convertToType(data['fdcId'], 'Number');
      if (data.hasOwnProperty('foodNutrients'))
        obj.foodNutrients = ApiClient.convertToType(data['foodNutrients'], [AbridgedFoodNutrient]);
      if (data.hasOwnProperty('publicationDate'))
        obj.publicationDate = ApiClient.convertToType(data['publicationDate'], 'String');
      if (data.hasOwnProperty('brandOwner'))
        obj.brandOwner = ApiClient.convertToType(data['brandOwner'], 'String');
      if (data.hasOwnProperty('gtinUpc'))
        obj.gtinUpc = ApiClient.convertToType(data['gtinUpc'], 'String');
      if (data.hasOwnProperty('ndbNumber'))
        obj.ndbNumber = ApiClient.convertToType(data['ndbNumber'], 'Number');
      if (data.hasOwnProperty('foodCode'))
        obj.foodCode = ApiClient.convertToType(data['foodCode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} dataType
 */
AbridgedFoodItem.prototype.dataType = undefined;

/**
 * @member {String} description
 */
AbridgedFoodItem.prototype.description = undefined;

/**
 * @member {Number} fdcId
 */
AbridgedFoodItem.prototype.fdcId = undefined;

/**
 * @member {Array.<module:model/AbridgedFoodNutrient>} foodNutrients
 */
AbridgedFoodItem.prototype.foodNutrients = undefined;

/**
 * @member {String} publicationDate
 */
AbridgedFoodItem.prototype.publicationDate = undefined;

/**
 * only applies to Branded Foods
 * @member {String} brandOwner
 */
AbridgedFoodItem.prototype.brandOwner = undefined;

/**
 * only applies to Branded Foods
 * @member {String} gtinUpc
 */
AbridgedFoodItem.prototype.gtinUpc = undefined;

/**
 * only applies to Foundation and SRLegacy Foods
 * @member {Number} ndbNumber
 */
AbridgedFoodItem.prototype.ndbNumber = undefined;

/**
 * only applies to Survey Foods
 * @member {String} foodCode
 */
AbridgedFoodItem.prototype.foodCode = undefined;

// Implement InlineResponse200 interface:
