/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from .js';

/**
 * The FoodSearchCriteria model module.
 * @module model/FoodSearchCriteria
 * @version 1.0.1
 */
export class FoodSearchCriteria {
  /**
   * Constructs a new <code>FoodSearchCriteria</code>.
   * A copy of the criteria that were used in the search.
   * @alias module:model/FoodSearchCriteria
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FoodSearchCriteria</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FoodSearchCriteria} obj Optional instance to populate.
   * @return {module:model/FoodSearchCriteria} The populated <code>FoodSearchCriteria</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FoodSearchCriteria();
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
      if (data.hasOwnProperty('dataType'))
        obj.dataType = ApiClient.convertToType(data['dataType'], ['String']);
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('pageNumber'))
        obj.pageNumber = ApiClient.convertToType(data['pageNumber'], 'Number');
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
      if (data.hasOwnProperty('brandOwner'))
        obj.brandOwner = ApiClient.convertToType(data['brandOwner'], 'String');
      if (data.hasOwnProperty('tradeChannel'))
        obj.tradeChannel = ApiClient.convertToType(data['tradeChannel'], ['String']);
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'String');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'String');
    }
    return obj;
  }
}

/**
 * Search terms to use in the search. The string may also include standard [search operators](https://fdc.nal.usda.gov/help.html#bkmk-2)
 * @member {String} query
 */
FoodSearchCriteria.prototype.query = undefined;

/**
 * Allowed values for the <code>dataType</code> property.
 * @enum {String}
 * @readonly
 */
FoodSearchCriteria.DataTypeEnum = {
  /**
   * value: "Branded"
   * @const
   */
  branded: "Branded",

  /**
   * value: "Foundation"
   * @const
   */
  foundation: "Foundation",

  /**
   * value: "Survey (FNDDS)"
   * @const
   */
  surveyFNDDS: "Survey (FNDDS)",

  /**
   * value: "SR Legacy"
   * @const
   */
  sRLegacy: "SR Legacy"
};
/**
 * Optional. Filter on a specific data type; specify one or more values in an array.
 * @member {Array.<module:model/FoodSearchCriteria.DataTypeEnum>} dataType
 */
FoodSearchCriteria.prototype.dataType = undefined;

/**
 * Optional. Maximum number of results to return for the current page. Default is 50.
 * @member {Number} pageSize
 */
FoodSearchCriteria.prototype.pageSize = undefined;

/**
 * Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
 * @member {Number} pageNumber
 */
FoodSearchCriteria.prototype.pageNumber = undefined;

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
FoodSearchCriteria.SortByEnum = {
  /**
   * value: "dataType.keyword"
   * @const
   */
  dataTypeKeyword: "dataType.keyword",

  /**
   * value: "lowercaseDescription.keyword"
   * @const
   */
  lowercaseDescriptionKeyword: "lowercaseDescription.keyword",

  /**
   * value: "fdcId"
   * @const
   */
  fdcId: "fdcId",

  /**
   * value: "publishedDate"
   * @const
   */
  publishedDate: "publishedDate"
};
/**
 * Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and description.keyword will be description in future releases.
 * @member {module:model/FoodSearchCriteria.SortByEnum} sortBy
 */
FoodSearchCriteria.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
FoodSearchCriteria.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Optional. The sort direction for the results. Only applicable if sortBy is specified.
 * @member {module:model/FoodSearchCriteria.SortOrderEnum} sortOrder
 */
FoodSearchCriteria.prototype.sortOrder = undefined;

/**
 * Optional. Filter results based on the brand owner of the food. Only applies to Branded Foods.
 * @member {String} brandOwner
 */
FoodSearchCriteria.prototype.brandOwner = undefined;

/**
 * Allowed values for the <code>tradeChannel</code> property.
 * @enum {String}
 * @readonly
 */
FoodSearchCriteria.TradeChannelEnum = {
  /**
   * value: "CHILD_NUTRITION_FOOD_PROGRAMS"
   * @const
   */
  CHILD_NUTRITION_FOOD_PROGRAMS: "CHILD_NUTRITION_FOOD_PROGRAMS",

  /**
   * value: "DRUG"
   * @const
   */
  DRUG: "DRUG",

  /**
   * value: "FOOD_SERVICE"
   * @const
   */
  FOOD_SERVICE: "FOOD_SERVICE",

  /**
   * value: "GROCERY"
   * @const
   */
  GROCERY: "GROCERY",

  /**
   * value: "MASS_MERCHANDISING"
   * @const
   */
  MASS_MERCHANDISING: "MASS_MERCHANDISING",

  /**
   * value: "MILITARY"
   * @const
   */
  MILITARY: "MILITARY",

  /**
   * value: "ONLINE"
   * @const
   */
  ONLINE: "ONLINE",

  /**
   * value: "VENDING"
   * @const
   */
  VENDING: "VENDING"
};
/**
 * Optional. Filter foods containing any of the specified trade channels.
 * @member {Array.<module:model/FoodSearchCriteria.TradeChannelEnum>} tradeChannel
 */
FoodSearchCriteria.prototype.tradeChannel = undefined;

/**
 * Filter foods published on or after this date. Format: YYYY-MM-DD
 * @member {String} startDate
 */
FoodSearchCriteria.prototype.startDate = undefined;

/**
 * Filter foods published on or before this date. Format: YYYY-MM-DD
 * @member {String} endDate
 */
FoodSearchCriteria.prototype.endDate = undefined;

