/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FoodListCriteria model module.
 * @module model/FoodListCriteria
 * @version 1.0.1
 */
export class FoodListCriteria {
  /**
   * Constructs a new <code>FoodListCriteria</code>.
   * JSON for request body of &#x27;list&#x27; POST request
   * @alias module:model/FoodListCriteria
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FoodListCriteria</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FoodListCriteria} obj Optional instance to populate.
   * @return {module:model/FoodListCriteria} The populated <code>FoodListCriteria</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FoodListCriteria();
      if (data.hasOwnProperty('dataType'))
        obj.dataType = ApiClient.convertToType(data['dataType'], ['String']);
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('pageNumber'))
        obj.pageNumber = ApiClient.convertToType(data['pageNumber'], 'Number');
      if (data.hasOwnProperty('sortBy'))
        obj.sortBy = ApiClient.convertToType(data['sortBy'], 'String');
      if (data.hasOwnProperty('sortOrder'))
        obj.sortOrder = ApiClient.convertToType(data['sortOrder'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>dataType</code> property.
 * @enum {String}
 * @readonly
 */
FoodListCriteria.DataTypeEnum = {
  /**
   * value: "Branded"
   * @const
   */
  branded: "Branded",

  /**
   * value: "Foundation"
   * @const
   */
  foundation: "Foundation",

  /**
   * value: "Survey (FNDDS)"
   * @const
   */
  surveyFNDDS: "Survey (FNDDS)",

  /**
   * value: "SR Legacy"
   * @const
   */
  sRLegacy: "SR Legacy"
};
/**
 * Optional. Filter on a specific data type; specify one or more values in an array.
 * @member {Array.<module:model/FoodListCriteria.DataTypeEnum>} dataType
 */
FoodListCriteria.prototype.dataType = undefined;

/**
 * Optional. Maximum number of results to return for the current page. Default is 50.
 * @member {Number} pageSize
 */
FoodListCriteria.prototype.pageSize = undefined;

/**
 * Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
 * @member {Number} pageNumber
 */
FoodListCriteria.prototype.pageNumber = undefined;

/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
FoodListCriteria.SortByEnum = {
  /**
   * value: "dataType.keyword"
   * @const
   */
  dataTypeKeyword: "dataType.keyword",

  /**
   * value: "lowercaseDescription.keyword"
   * @const
   */
  lowercaseDescriptionKeyword: "lowercaseDescription.keyword",

  /**
   * value: "fdcId"
   * @const
   */
  fdcId: "fdcId",

  /**
   * value: "publishedDate"
   * @const
   */
  publishedDate: "publishedDate"
};
/**
 * Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
 * @member {module:model/FoodListCriteria.SortByEnum} sortBy
 */
FoodListCriteria.prototype.sortBy = undefined;

/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
FoodListCriteria.SortOrderEnum = {
  /**
   * value: "asc"
   * @const
   */
  asc: "asc",

  /**
   * value: "desc"
   * @const
   */
  desc: "desc"
};
/**
 * Optional. The sort direction for the results. Only applicable if sortBy is specified.
 * @member {module:model/FoodListCriteria.SortOrderEnum} sortOrder
 */
FoodListCriteria.prototype.sortOrder = undefined;

