/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodDataCentralApi);
  }
}(this, function(expect, FoodDataCentralApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FoodNutrient', function() {
      beforeEach(function() {
        instance = new FoodDataCentralApi.FoodNutrient();
      });

      it('should create an instance of FoodNutrient', function() {
        // TODO: update the code to test FoodNutrient
        expect(instance).to.be.a(FoodDataCentralApi.FoodNutrient);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property dataPoints (base name: "dataPoints")', function() {
        // TODO: update the code to test the property dataPoints
        expect(instance).to.have.property('dataPoints');
        // expect(instance.dataPoints).to.be(expectedValueLiteral);
      });

      it('should have the property min (base name: "min")', function() {
        // TODO: update the code to test the property min
        expect(instance).to.have.property('min');
        // expect(instance.min).to.be(expectedValueLiteral);
      });

      it('should have the property max (base name: "max")', function() {
        // TODO: update the code to test the property max
        expect(instance).to.have.property('max');
        // expect(instance.max).to.be(expectedValueLiteral);
      });

      it('should have the property median (base name: "median")', function() {
        // TODO: update the code to test the property median
        expect(instance).to.have.property('median');
        // expect(instance.median).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property nutrient (base name: "nutrient")', function() {
        // TODO: update the code to test the property nutrient
        expect(instance).to.have.property('nutrient');
        // expect(instance.nutrient).to.be(expectedValueLiteral);
      });

      it('should have the property foodNutrientDerivation (base name: "foodNutrientDerivation")', function() {
        // TODO: update the code to test the property foodNutrientDerivation
        expect(instance).to.have.property('foodNutrientDerivation');
        // expect(instance.foodNutrientDerivation).to.be(expectedValueLiteral);
      });

      it('should have the property nutrientAnalysisDetails (base name: "nutrientAnalysisDetails")', function() {
        // TODO: update the code to test the property nutrientAnalysisDetails
        expect(instance).to.have.property('nutrientAnalysisDetails');
        // expect(instance.nutrientAnalysisDetails).to.be(expectedValueLiteral);
      });

    });
  });

}));
