/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodDataCentralApi);
  }
}(this, function(expect, FoodDataCentralApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('FoodSearchCriteria', function() {
      beforeEach(function() {
        instance = new FoodDataCentralApi.FoodSearchCriteria();
      });

      it('should create an instance of FoodSearchCriteria', function() {
        // TODO: update the code to test FoodSearchCriteria
        expect(instance).to.be.a(FoodDataCentralApi.FoodSearchCriteria);
      });

      it('should have the property query (base name: "query")', function() {
        // TODO: update the code to test the property query
        expect(instance).to.have.property('query');
        // expect(instance.query).to.be(expectedValueLiteral);
      });

      it('should have the property dataType (base name: "dataType")', function() {
        // TODO: update the code to test the property dataType
        expect(instance).to.have.property('dataType');
        // expect(instance.dataType).to.be(expectedValueLiteral);
      });

      it('should have the property pageSize (base name: "pageSize")', function() {
        // TODO: update the code to test the property pageSize
        expect(instance).to.have.property('pageSize');
        // expect(instance.pageSize).to.be(expectedValueLiteral);
      });

      it('should have the property pageNumber (base name: "pageNumber")', function() {
        // TODO: update the code to test the property pageNumber
        expect(instance).to.have.property('pageNumber');
        // expect(instance.pageNumber).to.be(expectedValueLiteral);
      });

      it('should have the property sortBy (base name: "sortBy")', function() {
        // TODO: update the code to test the property sortBy
        expect(instance).to.have.property('sortBy');
        // expect(instance.sortBy).to.be(expectedValueLiteral);
      });

      it('should have the property sortOrder (base name: "sortOrder")', function() {
        // TODO: update the code to test the property sortOrder
        expect(instance).to.have.property('sortOrder');
        // expect(instance.sortOrder).to.be(expectedValueLiteral);
      });

      it('should have the property brandOwner (base name: "brandOwner")', function() {
        // TODO: update the code to test the property brandOwner
        expect(instance).to.have.property('brandOwner');
        // expect(instance.brandOwner).to.be(expectedValueLiteral);
      });

      it('should have the property tradeChannel (base name: "tradeChannel")', function() {
        // TODO: update the code to test the property tradeChannel
        expect(instance).to.have.property('tradeChannel');
        // expect(instance.tradeChannel).to.be(expectedValueLiteral);
      });

      it('should have the property startDate (base name: "startDate")', function() {
        // TODO: update the code to test the property startDate
        expect(instance).to.have.property('startDate');
        // expect(instance.startDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "endDate")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

    });
  });

}));
