/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodDataCentralApi);
  }
}(this, function(expect, FoodDataCentralApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SearchResultFood', function() {
      beforeEach(function() {
        instance = new FoodDataCentralApi.SearchResultFood();
      });

      it('should create an instance of SearchResultFood', function() {
        // TODO: update the code to test SearchResultFood
        expect(instance).to.be.a(FoodDataCentralApi.SearchResultFood);
      });

      it('should have the property fdcId (base name: "fdcId")', function() {
        // TODO: update the code to test the property fdcId
        expect(instance).to.have.property('fdcId');
        // expect(instance.fdcId).to.be(expectedValueLiteral);
      });

      it('should have the property dataType (base name: "dataType")', function() {
        // TODO: update the code to test the property dataType
        expect(instance).to.have.property('dataType');
        // expect(instance.dataType).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property foodCode (base name: "foodCode")', function() {
        // TODO: update the code to test the property foodCode
        expect(instance).to.have.property('foodCode');
        // expect(instance.foodCode).to.be(expectedValueLiteral);
      });

      it('should have the property foodNutrients (base name: "foodNutrients")', function() {
        // TODO: update the code to test the property foodNutrients
        expect(instance).to.have.property('foodNutrients');
        // expect(instance.foodNutrients).to.be(expectedValueLiteral);
      });

      it('should have the property publicationDate (base name: "publicationDate")', function() {
        // TODO: update the code to test the property publicationDate
        expect(instance).to.have.property('publicationDate');
        // expect(instance.publicationDate).to.be(expectedValueLiteral);
      });

      it('should have the property scientificName (base name: "scientificName")', function() {
        // TODO: update the code to test the property scientificName
        expect(instance).to.have.property('scientificName');
        // expect(instance.scientificName).to.be(expectedValueLiteral);
      });

      it('should have the property brandOwner (base name: "brandOwner")', function() {
        // TODO: update the code to test the property brandOwner
        expect(instance).to.have.property('brandOwner');
        // expect(instance.brandOwner).to.be(expectedValueLiteral);
      });

      it('should have the property gtinUpc (base name: "gtinUpc")', function() {
        // TODO: update the code to test the property gtinUpc
        expect(instance).to.have.property('gtinUpc');
        // expect(instance.gtinUpc).to.be(expectedValueLiteral);
      });

      it('should have the property ingredients (base name: "ingredients")', function() {
        // TODO: update the code to test the property ingredients
        expect(instance).to.have.property('ingredients');
        // expect(instance.ingredients).to.be(expectedValueLiteral);
      });

      it('should have the property ndbNumber (base name: "ndbNumber")', function() {
        // TODO: update the code to test the property ndbNumber
        expect(instance).to.have.property('ndbNumber');
        // expect(instance.ndbNumber).to.be(expectedValueLiteral);
      });

      it('should have the property additionalDescriptions (base name: "additionalDescriptions")', function() {
        // TODO: update the code to test the property additionalDescriptions
        expect(instance).to.have.property('additionalDescriptions');
        // expect(instance.additionalDescriptions).to.be(expectedValueLiteral);
      });

      it('should have the property allHighlightFields (base name: "allHighlightFields")', function() {
        // TODO: update the code to test the property allHighlightFields
        expect(instance).to.have.property('allHighlightFields');
        // expect(instance.allHighlightFields).to.be(expectedValueLiteral);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

    });
  });

}));
