/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient.js';
import {AbridgedFoodItem} from './model/AbridgedFoodItem.js';
import {AbridgedFoodNutrient} from './model/AbridgedFoodNutrient.js';
import {BrandedFoodItem} from './model/BrandedFoodItem.js';
import {BrandedFoodItemLabelNutrients} from './model/BrandedFoodItemLabelNutrients.js';
import {BrandedFoodItemLabelNutrientsCalcium} from './model/BrandedFoodItemLabelNutrientsCalcium.js';
import {BrandedFoodItemLabelNutrientsCalories} from './model/BrandedFoodItemLabelNutrientsCalories.js';
import {BrandedFoodItemLabelNutrientsCarbohydrates} from './model/BrandedFoodItemLabelNutrientsCarbohydrates.js';
import {BrandedFoodItemLabelNutrientsFat} from './model/BrandedFoodItemLabelNutrientsFat.js';
import {BrandedFoodItemLabelNutrientsFiber} from './model/BrandedFoodItemLabelNutrientsFiber.js';
import {BrandedFoodItemLabelNutrientsIron} from './model/BrandedFoodItemLabelNutrientsIron.js';
import {BrandedFoodItemLabelNutrientsPotassium} from './model/BrandedFoodItemLabelNutrientsPotassium.js';
import {BrandedFoodItemLabelNutrientsProtein} from './model/BrandedFoodItemLabelNutrientsProtein.js';
import {BrandedFoodItemLabelNutrientsSaturatedFat} from './model/BrandedFoodItemLabelNutrientsSaturatedFat.js';
import {BrandedFoodItemLabelNutrientsSugars} from './model/BrandedFoodItemLabelNutrientsSugars.js';
import {BrandedFoodItemLabelNutrientsTransFat} from './model/BrandedFoodItemLabelNutrientsTransFat.js';
import {FoodAttribute} from './model/FoodAttribute.js';
import {FoodAttributeFoodAttributeType} from './model/FoodAttributeFoodAttributeType.js';
import {FoodCategory} from './model/FoodCategory.js';
import {FoodComponent} from './model/FoodComponent.js';
import {FoodListCriteria} from './model/FoodListCriteria.js';
import {FoodNutrient} from './model/FoodNutrient.js';
import {FoodNutrientDerivation} from './model/FoodNutrientDerivation.js';
import {FoodNutrientSource} from './model/FoodNutrientSource.js';
import {FoodPortion} from './model/FoodPortion.js';
import {FoodSearchCriteria} from './model/FoodSearchCriteria.js';
import {FoodUpdateLog} from './model/FoodUpdateLog.js';
import {FoodsCriteria} from './model/FoodsCriteria.js';
import {FoundationFoodItem} from './model/FoundationFoodItem.js';
import {InlineResponse200} from './model/InlineResponse200.js';
import {InputFoodFoundation} from './model/InputFoodFoundation.js';
import {InputFoodSurvey} from './model/InputFoodSurvey.js';
import {MeasureUnit} from './model/MeasureUnit.js';
import {Nutrient} from './model/Nutrient.js';
import {NutrientAcquisitionDetails} from './model/NutrientAcquisitionDetails.js';
import {NutrientAnalysisDetails} from './model/NutrientAnalysisDetails.js';
import {NutrientConversionFactors} from './model/NutrientConversionFactors.js';
import {RetentionFactor} from './model/RetentionFactor.js';
import {SRLegacyFoodItem} from './model/SRLegacyFoodItem.js';
import {SampleFoodItem} from './model/SampleFoodItem.js';
import {SearchResult} from './model/SearchResult.js';
import {SearchResultFood} from './model/SearchResultFood.js';
import {SurveyFoodItem} from './model/SurveyFoodItem.js';
import {WweiaFoodCategory} from './model/WweiaFoodCategory.js';
import {FDCApi} from './api/FDCApi.js';

/**
* The_FoodData_Central_API_provides_REST_access_to_FoodData_Central__FDC__It_is_intended_primarily_to_assist_application_developers_wishing_to_incorporate_nutrient_data_into_their_applications_or_websites___To_take_full_advantage_of_the_API_developers_should_familiarize_themselves_with_the_database_by_reading_the_database_documentation_available_via_links_on__Data_Type_Documentation_httpsfdc_nal_usda_govdata_documentation_html__This_documentation_provides_the_detailed_definitions_and_descriptions_needed_to_understand_the_data_elements_referenced_in_the_API_documentation_____Additional_details_about_the_API_including_rate_limits_access_and_licensing_are_available_on_the__FDC_website_httpsfdc_nal_usda_govapi_guide_html.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FoodDataCentralApi = require('index'); // See note below*.
* var xxxSvc = new FoodDataCentralApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FoodDataCentralApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FoodDataCentralApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FoodDataCentralApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AbridgedFoodItem model constructor.
     * @property {module:model/AbridgedFoodItem}
     */
    AbridgedFoodItem,

    /**
     * The AbridgedFoodNutrient model constructor.
     * @property {module:model/AbridgedFoodNutrient}
     */
    AbridgedFoodNutrient,

    /**
     * The BrandedFoodItem model constructor.
     * @property {module:model/BrandedFoodItem}
     */
    BrandedFoodItem,

    /**
     * The BrandedFoodItemLabelNutrients model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrients}
     */
    BrandedFoodItemLabelNutrients,

    /**
     * The BrandedFoodItemLabelNutrientsCalcium model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsCalcium}
     */
    BrandedFoodItemLabelNutrientsCalcium,

    /**
     * The BrandedFoodItemLabelNutrientsCalories model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsCalories}
     */
    BrandedFoodItemLabelNutrientsCalories,

    /**
     * The BrandedFoodItemLabelNutrientsCarbohydrates model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsCarbohydrates}
     */
    BrandedFoodItemLabelNutrientsCarbohydrates,

    /**
     * The BrandedFoodItemLabelNutrientsFat model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsFat}
     */
    BrandedFoodItemLabelNutrientsFat,

    /**
     * The BrandedFoodItemLabelNutrientsFiber model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsFiber}
     */
    BrandedFoodItemLabelNutrientsFiber,

    /**
     * The BrandedFoodItemLabelNutrientsIron model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsIron}
     */
    BrandedFoodItemLabelNutrientsIron,

    /**
     * The BrandedFoodItemLabelNutrientsPotassium model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsPotassium}
     */
    BrandedFoodItemLabelNutrientsPotassium,

    /**
     * The BrandedFoodItemLabelNutrientsProtein model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsProtein}
     */
    BrandedFoodItemLabelNutrientsProtein,

    /**
     * The BrandedFoodItemLabelNutrientsSaturatedFat model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsSaturatedFat}
     */
    BrandedFoodItemLabelNutrientsSaturatedFat,

    /**
     * The BrandedFoodItemLabelNutrientsSugars model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsSugars}
     */
    BrandedFoodItemLabelNutrientsSugars,

    /**
     * The BrandedFoodItemLabelNutrientsTransFat model constructor.
     * @property {module:model/BrandedFoodItemLabelNutrientsTransFat}
     */
    BrandedFoodItemLabelNutrientsTransFat,

    /**
     * The FoodAttribute model constructor.
     * @property {module:model/FoodAttribute}
     */
    FoodAttribute,

    /**
     * The FoodAttributeFoodAttributeType model constructor.
     * @property {module:model/FoodAttributeFoodAttributeType}
     */
    FoodAttributeFoodAttributeType,

    /**
     * The FoodCategory model constructor.
     * @property {module:model/FoodCategory}
     */
    FoodCategory,

    /**
     * The FoodComponent model constructor.
     * @property {module:model/FoodComponent}
     */
    FoodComponent,

    /**
     * The FoodListCriteria model constructor.
     * @property {module:model/FoodListCriteria}
     */
    FoodListCriteria,

    /**
     * The FoodNutrient model constructor.
     * @property {module:model/FoodNutrient}
     */
    FoodNutrient,

    /**
     * The FoodNutrientDerivation model constructor.
     * @property {module:model/FoodNutrientDerivation}
     */
    FoodNutrientDerivation,

    /**
     * The FoodNutrientSource model constructor.
     * @property {module:model/FoodNutrientSource}
     */
    FoodNutrientSource,

    /**
     * The FoodPortion model constructor.
     * @property {module:model/FoodPortion}
     */
    FoodPortion,

    /**
     * The FoodSearchCriteria model constructor.
     * @property {module:model/FoodSearchCriteria}
     */
    FoodSearchCriteria,

    /**
     * The FoodUpdateLog model constructor.
     * @property {module:model/FoodUpdateLog}
     */
    FoodUpdateLog,

    /**
     * The FoodsCriteria model constructor.
     * @property {module:model/FoodsCriteria}
     */
    FoodsCriteria,

    /**
     * The FoundationFoodItem model constructor.
     * @property {module:model/FoundationFoodItem}
     */
    FoundationFoodItem,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InputFoodFoundation model constructor.
     * @property {module:model/InputFoodFoundation}
     */
    InputFoodFoundation,

    /**
     * The InputFoodSurvey model constructor.
     * @property {module:model/InputFoodSurvey}
     */
    InputFoodSurvey,

    /**
     * The MeasureUnit model constructor.
     * @property {module:model/MeasureUnit}
     */
    MeasureUnit,

    /**
     * The Nutrient model constructor.
     * @property {module:model/Nutrient}
     */
    Nutrient,

    /**
     * The NutrientAcquisitionDetails model constructor.
     * @property {module:model/NutrientAcquisitionDetails}
     */
    NutrientAcquisitionDetails,

    /**
     * The NutrientAnalysisDetails model constructor.
     * @property {module:model/NutrientAnalysisDetails}
     */
    NutrientAnalysisDetails,

    /**
     * The NutrientConversionFactors model constructor.
     * @property {module:model/NutrientConversionFactors}
     */
    NutrientConversionFactors,

    /**
     * The RetentionFactor model constructor.
     * @property {module:model/RetentionFactor}
     */
    RetentionFactor,

    /**
     * The SRLegacyFoodItem model constructor.
     * @property {module:model/SRLegacyFoodItem}
     */
    SRLegacyFoodItem,

    /**
     * The SampleFoodItem model constructor.
     * @property {module:model/SampleFoodItem}
     */
    SampleFoodItem,

    /**
     * The SearchResult model constructor.
     * @property {module:model/SearchResult}
     */
    SearchResult,

    /**
     * The SearchResultFood model constructor.
     * @property {module:model/SearchResultFood}
     */
    SearchResultFood,

    /**
     * The SurveyFoodItem model constructor.
     * @property {module:model/SurveyFoodItem}
     */
    SurveyFoodItem,

    /**
     * The WweiaFoodCategory model constructor.
     * @property {module:model/WweiaFoodCategory}
     */
    WweiaFoodCategory,

    /**
    * The FDCApi service constructor.
    * @property {module:api/FDCApi}
    */
    FDCApi
};
