/*
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FoodDataCentralApi);
  }
}(this, function(expect, FoodDataCentralApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FoodDataCentralApi.FDCApi();
  });

  describe('(package)', function() {
    describe('FDCApi', function() {
      describe('getFood', function() {
        it('should call getFood successfully', function(done) {
          // TODO: uncomment, update parameter values for getFood call and complete the assertions
          /*
          var opts = {};

          instance.getFood(fdcId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FoodDataCentralApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getFoods', function() {
        it('should call getFoods successfully', function(done) {
          // TODO: uncomment, update parameter values for getFoods call and complete the assertions
          /*
          var opts = {};

          instance.getFoods(fdcIds, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Object);
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getFoodsList', function() {
        it('should call getFoodsList successfully', function(done) {
          // TODO: uncomment, update parameter values for getFoodsList call and complete the assertions
          /*
          var opts = {};

          instance.getFoodsList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FoodDataCentralApi.AbridgedFoodItem);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getFoodsSearch', function() {
        it('should call getFoodsSearch successfully', function(done) {
          // TODO: uncomment, update parameter values for getFoodsSearch call and complete the assertions
          /*
          var opts = {};

          instance.getFoodsSearch(query, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FoodDataCentralApi.SearchResult);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getJsonSpec', function() {
        it('should call getJsonSpec successfully', function(done) {
          // TODO: uncomment getJsonSpec call
          /*

          instance.getJsonSpec(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getYamlSpec', function() {
        it('should call getYamlSpec successfully', function(done) {
          // TODO: uncomment getYamlSpec call
          /*

          instance.getYamlSpec(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postFoods', function() {
        it('should call postFoods successfully', function(done) {
          // TODO: uncomment, update parameter values for postFoods call and complete the assertions
          /*

          instance.postFoods(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Object);
              // expect(data).to.be(null);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postFoodsList', function() {
        it('should call postFoodsList successfully', function(done) {
          // TODO: uncomment, update parameter values for postFoodsList call and complete the assertions
          /*

          instance.postFoodsList(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FoodDataCentralApi.AbridgedFoodItem);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postFoodsSearch', function() {
        it('should call postFoodsSearch successfully', function(done) {
          // TODO: uncomment, update parameter values for postFoodsSearch call and complete the assertions
          /*

          instance.postFoodsSearch(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FoodDataCentralApi.SearchResult);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
